/* SIGNIN */

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

/* SIGNUP */

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

/* TOKEN */

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

/* LOGOUT */

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

/* USER INFO */

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

/* FORGOT PASSWORD  */

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

/* NOTIFICATIONS */

export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE';

/* NOTIFICATIONS READ */

export const NOTIFICATIONS_READ_REQUEST = 'NOTIFICATIONS_READ_REQUEST';
export const NOTIFICATIONS_READ_SUCCESS = 'NOTIFICATIONS_READ_SUCCESS';
export const NOTIFICATIONS_READ_FAILURE = 'NOTIFICATIONS_READ_FAILURE';

/* CALENDER  */

export const CALENDER_BOOKINGS_INFO_REQUEST = 'CALENDER_BOOKINGS_INFO_REQUEST';
export const CALENDER_BOOKINGS_INFO_SUCCESS = 'CALENDER_BOOKINGS_INFO_SUCCESS';
export const CALENDER_BOOKINGS_INFO_FAILURE = 'CALENDER_BOOKINGS_INFO_FAILURE';

/* UPCOMING_BOOKING  */

export const UPCOMING_BOOKING_REQUEST = 'UPCOMING_BOOKING_REQUEST';
export const UPCOMING_BOOKING_SUCCESS = 'UPCOMING_BOOKING_SUCCESS';
export const UPCOMING_BOOKING_FAILURE = 'UPCOMING_BOOKING_FAILURE';

/* DUE_BOOKING  */

export const DUE_BOOKING_REQUEST = 'DUE_BOOKING_REQUEST';
export const DUE_BOOKING_SUCCESS = 'DUE_BOOKING_SUCCESS';
export const DUE_BOOKING_FAILURE = 'DUE_BOOKING_FAILURE';

/* ALL  BOOKING */

export const ALL_BOOKINGS_REQUEST = 'ALL_BOOKINGS_REQUEST';
export const ALL_BOOKINGS_SUCCESS = 'ALL_BOOKINGS_SUCCESS';
export const ALL_BOOKINGS_FAILURE = 'ALL_BOOKINGS_FAILURE';

/* ALL  MEMBERS */

export const ALL_MEMBERS_REQUEST = 'ALL_MEMBERS_REQUEST';
export const ALL_MEMBERS_SUCCESS = 'ALL_MEMBERS_SUCCESS';
export const ALL_MEMBERS_FAILURE = 'ALL_MEMBERS_FAILURE';

/* INVITE STATUS */

export const INVITE_STATUS_REQUEST = 'INVITE_STATUS_REQUEST';
export const INVITE_STATUS_SUCCESS = 'INVITE_STATUS_SUCCESS';
export const INVITE_STATUS_FAILURE = 'INVITE_STATUS_FAILURE';

/* VERIFY_OTP_SIGNUP */

export const VERIFY_OTP_SIGNUP_REQUEST = 'VERIFY_OTP_SIGNUP_REQUEST';
export const VERIFY_OTP_SIGNUP_SUCCESS = 'VERIFY_OTP_SIGNUP_SUCCESS';
export const VERIFY_OTP_SIGNUP_FAILURE = 'VERIFY_OTP_SIGNUP_FAILURE';

/* VERIFY_OTP_FORGOT_PASSWORD */

export const VERIFY_OTP_FORGOT_PASSWORD_REQUEST =
  'VERIFY_OTP_FORGOT_PASSWORD_REQUEST';
export const VERIFY_OTP_FORGOT_PASSWORD_SUCCESS =
  'VERIFY_OTP_FORGOT_PASSWORD_SUCCESS';
export const VERIFY_OTP_FORGOT_PASSWORD_FAILURE =
  'VERIFY_OTP_FORGOT_PASSWORD_FAILURE';
