/* SIGNIN */

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

/* SIGNUP */

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

/* TOKEN */

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

/* LOGOUT */

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

/* USER INFO */

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

/* FORGOT PASSWORD  */

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

/* NOTIFICATIONS */

export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE';

/* NOTIFICATIONS READ */

export const NOTIFICATIONS_READ_REQUEST = 'NOTIFICATIONS_READ_REQUEST';
export const NOTIFICATIONS_READ_SUCCESS = 'NOTIFICATIONS_READ_SUCCESS';
export const NOTIFICATIONS_READ_FAILURE = 'NOTIFICATIONS_READ_FAILURE';

/* CALENDER  */

export const CALENDER_BOOKINGS_INFO_REQUEST = 'CALENDER_BOOKINGS_INFO_REQUEST';
export const CALENDER_BOOKINGS_INFO_SUCCESS = 'CALENDER_BOOKINGS_INFO_SUCCESS';
export const CALENDER_BOOKINGS_INFO_FAILURE = 'CALENDER_BOOKINGS_INFO_FAILURE';

/* UPCOMING_BOOKING  */

export const UPCOMING_BOOKING_REQUEST = 'UPCOMING_BOOKING_REQUEST';
export const UPCOMING_BOOKING_SUCCESS = 'UPCOMING_BOOKING_SUCCESS';
export const UPCOMING_BOOKING_FAILURE = 'UPCOMING_BOOKING_FAILURE';

/* DUE_BOOKING  */

export const DUE_BOOKING_REQUEST = 'DUE_BOOKING_REQUEST';
export const DUE_BOOKING_SUCCESS = 'DUE_BOOKING_SUCCESS';
export const DUE_BOOKING_FAILURE = 'DUE_BOOKING_FAILURE';

/* ALL  BOOKING */

export const ALL_BOOKINGS_REQUEST = 'ALL_BOOKINGS_REQUEST';
export const ALL_BOOKINGS_SUCCESS = 'ALL_BOOKINGS_SUCCESS';
export const ALL_BOOKINGS_FAILURE = 'ALL_BOOKINGS_FAILURE';

/* GET  BOOKING BY DATE*/

export const GET_BOOKINGS_BY_DATE_REQUEST = 'GET_BOOKINGS_BY_DATE_REQUEST';
export const GET_BOOKINGS_BY_DATE_SUCCESS = 'GET_BOOKINGS_BY_DATE_SUCCESS';
export const GET_BOOKINGS_BY_DATE_FAILURE = 'GET_BOOKINGS_BY_DATE_FAILURE';

/* ALL  MEMBERS */

export const ALL_MEMBERS_REQUEST = 'ALL_MEMBERS_REQUEST';
export const ALL_MEMBERS_SUCCESS = 'ALL_MEMBERS_SUCCESS';
export const ALL_MEMBERS_FAILURE = 'ALL_MEMBERS_FAILURE';

/* INVITE STATUS */

export const INVITE_STATUS_REQUEST = 'INVITE_STATUS_REQUEST';
export const INVITE_STATUS_SUCCESS = 'INVITE_STATUS_SUCCESS';
export const INVITE_STATUS_FAILURE = 'INVITE_STATUS_FAILURE';

/* VERIFY_OTP_SIGNUP */

export const VERIFY_OTP_SIGNUP_REQUEST = 'VERIFY_OTP_SIGNUP_REQUEST';
export const VERIFY_OTP_SIGNUP_SUCCESS = 'VERIFY_OTP_SIGNUP_SUCCESS';
export const VERIFY_OTP_SIGNUP_FAILURE = 'VERIFY_OTP_SIGNUP_FAILURE';

/* VERIFY_OTP_FORGOT_PASSWORD */

export const VERIFY_OTP_FORGOT_PASSWORD_REQUEST =
  'VERIFY_OTP_FORGOT_PASSWORD_REQUEST';
export const VERIFY_OTP_FORGOT_PASSWORD_SUCCESS =
  'VERIFY_OTP_FORGOT_PASSWORD_SUCCESS';
export const VERIFY_OTP_FORGOT_PASSWORD_FAILURE =
  'VERIFY_OTP_FORGOT_PASSWORD_FAILURE';

/* GET BOOKING DETAILS BY ID */

export const BOOKING_DETAILS_BY_ID_REQUEST = 'BOOKING_DETAILS_BY_ID_REQUEST';
export const BOOKING_DETAILS_BY_ID_SUCCESS = 'BOOKING_DETAILS_BY_ID_SUCCESS';
export const BOOKING_DETAILS_BY_ID_FAILURE = 'BOOKING_DETAILS_BY_ID_FAILURE';

/* HANDLE BOOKING (CANCLE,DUE,MISSING,PAID,PICKUP,RETURN,...)*/

export const HANDLE_BOOKING_CANCLE_REQUEST = 'HANDLE_BOOKING_CANCLE_REQUEST';
export const HANDLE_BOOKING_CANCLE_SUCCESS = 'HANDLE_BOOKING_CANCLE_SUCCESS';
export const HANDLE_BOOKING_CANCLE_FAILURE = 'HANDLE_BOOKING_CANCLE_FAILURE';

export const HANDLE_BOOKING_PICKUP_REQUEST = 'HANDLE_BOOKING_PICKUP_REQUEST';
export const HANDLE_BOOKING_PICKUP_SUCCESS = 'HANDLE_BOOKING_PICKUP_SUCCESS';
export const HANDLE_BOOKING_PICKUP_FAILURE = 'HANDLE_BOOKING_PICKUP_FAILURE';

export const HANDLE_BOOKING_RETURN_REQUEST = 'HANDLE_BOOKING_RETURN_REQUEST';
export const HANDLE_BOOKING_RETURN_SUCCESS = 'HANDLE_BOOKING_RETURN_SUCCESS';
export const HANDLE_BOOKING_RETURN_FAILURE = 'HANDLE_BOOKING_RETURN_FAILURE';

export const HANDLE_BOOKING_UPDATE_REQUEST = 'HANDLE_BOOKING_UPDATE_REQUEST';
export const HANDLE_BOOKING_UPDATE_SUCCESS = 'HANDLE_BOOKING_UPDATE_SUCCESS';
export const HANDLE_BOOKING_UPDATE_FAILURE = 'HANDLE_BOOKING_UPDATE_FAILURE';

export const HANDLE_BOOKING_MISSING_REQUEST = 'HANDLE_BOOKING_MISSING_REQUEST';
export const HANDLE_BOOKING_MISSING_SUCCESS = 'HANDLE_BOOKING_MISSING_SUCCESS';
export const HANDLE_BOOKING_MISSING_FAILURE = 'HANDLE_BOOKING_MISSING_FAILURE';

export const ADD_NEW_BOOKING_REQUEST = 'ADD_NEW_BOOKING_REQUEST';
export const ADD_NEW_BOOKING_SUCCESS = 'ADD_NEW_BOOKING_SUCCESS';
export const ADD_NEW_BOOKING_FAILURE = 'ADD_NEW_BOOKING_FAILURE';

/* ALL ITEM CHECK (CHECK-AVAILABILITY,CHECK-RETURN-ITEMS,INVENTORY-ITEMS....) */

export const CHECK_AVAILABILITY_REQUEST = 'CHECK_AVAILABILITY_REQUEST';
export const CHECK_AVAILABILITY_SUCCESS = 'CHECK_AVAILABILITY_SUCCESS';
export const CHECK_AVAILABILITY_FAILURE = 'CHECK_AVAILABILITY_FAILURE';

export const CHECK_RETURN_ITEM_REQUEST = 'CHECK_RETURN_ITEM_REQUEST';
export const CHECK_RETURN_ITEM_SUCCESS = 'CHECK_RETURN_ITEM_SUCCESS';
export const CHECK_RETURN_ITEM_FAILURE = 'CHECK_RETURN_ITEM_FAILURE';

export const GET_INVENTORY_ITEM_REQUEST = 'GET_INVENTORY_ITEM_REQUEST';
export const GET_INVENTORY_ITEM_SUCCESS = 'GET_INVENTORY_ITEM_SUCCESS';
export const GET_INVENTORY_ITEM_FAILURE = 'GET_INVENTORY_ITEM_FAILURE';
